# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pixtext.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from pixtext import Ui_MainWindow
#from pix2text import Pix2Text


class pixtext(Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi1(MainWindow)
        self.selected_file = ""
        self.textlist=[]
    def setupUi1(self, MainWindow):
        self.setupUi(MainWindow)
        self.pushButton.clicked.connect(self.openFile)
        self.letsgo.clicked.connect(self.recog)


    def p2timport(self):
        from pix2text import Pix2Text
        return Pix2Text


    def showpic(self):
        # 创建一个 QGraphicsScene 对象
        scene = QtWidgets.QGraphicsScene()

        # 加载图片并添加到场景中
        pixmap = QtGui.QPixmap(self.selected_file)
        scene.addPixmap(pixmap)

        # 将场景设置给 QGraphicsView 控件
        self.pictureshow.setScene(scene)

    def openFile(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(MainWindow, "选择文件", "", "All Files (*);;png (*.png)",
                                                            options=options)

        if fileName:
            self.selected_file = fileName
            self.lineEdit.setText(fileName)
            self.showpic()
            #print(fileName)
    def recog(self):
        self.textlist=[]
        p2t = self.p2timport()()
        out_text = p2t(self.selected_file)
        count = len(out_text)
        for i in range(count):
            self.textlist.append(out_text[i]['text'])
            print('公式：' + self.textlist[i])
            # pass
        # 使用列表推导式和 join() 方法合成一个包含回车的字符串
        self.combined_string = "\n".join([s.replace("$", "") for s in self.textlist])
        self.textEdit.setText(self.combined_string)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = pixtext()
    #ui.setupUi1(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
